aw

diff --git a/error_log b/error_log
--- a/error_log
+++ b/error_log
@@ -1,2 +1,174 @@
 [02-Feb-2022 03:32:40 UTC] PHP Warning:  Class 'Doctrine\Persistence\Mapping\ClassMetadata' not found in /home/bov/public_html/vendor/fakerphp/faker/src/Faker/ORM/Doctrine/backward-compatibility.php on line 6
 [02-Feb-2022 03:32:40 UTC] PHP Warning:  Class 'Doctrine\Persistence\ObjectManager' not found in /home/bov/public_html/vendor/fakerphp/faker/src/Faker/ORM/Doctrine/backward-compatibility.php on line 10
+[13-Feb-2022 11:52:11 America/Lima] An Error occurred while handling another error:
+yii\base\InvalidConfigException: Please configure UrlManager::scriptUrl correctly as you are running a console application. in /home/bov/public_html/vendor/yiisoft/yii2/web/UrlManager.php:619
+Stack trace:
+#0 /home/bov/public_html/vendor/yiisoft/yii2/web/UrlManager.php(419): yii\web\UrlManager->getScriptUrl()
+#1 /home/bov/public_html/vendor/yiisoft/yii2/helpers/BaseUrl.php(105): yii\web\UrlManager->createUrl(Array)
+#2 /home/bov/public_html/vendor/yiisoft/yii2/helpers/BaseUrl.php(214): yii\helpers\BaseUrl::toRoute(Array, false)
+#3 /home/bov/public_html/vendor/onmotion/yii2-telegram/Module.php(56): yii\helpers\BaseUrl::to(Array)
+#4 /home/bov/public_html/vendor/yiisoft/yii2/base/BaseObject.php(109): onmotion\telegram\Module->init()
+#5 /home/bov/public_html/vendor/yiisoft/yii2/base/Module.php(158): yii\base\BaseObject->__construct(Array)
+#6 [internal function]: yii\base\Module->__construct('telegram', Object(yii\console\Application), Array)
+#7 /home/bov/public_html/vendor/yiisoft/yii2/di/Container.php(420): ReflectionClass->newInstanceArgs(Array)
+#8 /home/bov/public_html/vendor/yiisoft/yii2/di/Container.php(171): yii\di\Container->build('onmotion\\telegr...', Array, Array)
+#9 /home/bov/public_html/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('onmotion\\telegr...', Array, Array)
+#10 /home/bov/public_html/vendor/yiisoft/yii2/base/Module.php(427): yii\BaseYii::createObject(Array, Array)
+#11 /home/bov/public_html/vendor/yiisoft/yii2/console/controllers/HelpController.php(237): yii\base\Module->getModule('telegram')
+#12 /home/bov/public_html/vendor/yiisoft/yii2/console/controllers/HelpController.php(172): yii\console\controllers\HelpController->getModuleCommands(Object(yii\console\Application))
+#13 /home/bov/public_html/vendor/yiisoft/yii2/console/UnknownCommandException.php(77): yii\console\controllers\HelpController->getCommands()
+#14 /home/bov/public_html/vendor/yiisoft/yii2/console/ErrorHandler.php(36): yii\console\UnknownCommandException->getSuggestedAlternatives()
+#15 /home/bov/public_html/vendor/yiisoft/yii2/base/ErrorHandler.php(135): yii\console\ErrorHandler->renderException(Object(yii\console\UnknownCommandException))
+#16 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\console\UnknownCommandException))
+#17 {main}
+Previous exception:
+yii\base\InvalidRouteException: Unable to resolve the request "migrate-module". in /home/bov/public_html/vendor/yiisoft/yii2/base/Module.php:543
+Stack trace:
+#0 /home/bov/public_html/vendor/yiisoft/yii2/console/Application.php(181): yii\base\Module->runAction('migrate-module', Array)
+#1 /home/bov/public_html/vendor/yiisoft/yii2/console/Application.php(148): yii\console\Application->runAction('migrate-module', Array)
+#2 /home/bov/public_html/vendor/yiisoft/yii2/base/Application.php(392): yii\console\Application->handleRequest(Object(yii\console\Request))
+#3 /home/bov/public_html/yii(23): yii\base\Application->run()
+#4 {main}
+
+Next yii\console\UnknownCommandException: Unknown command "migrate-module". in /home/bov/public_html/vendor/yiisoft/yii2/console/Application.php:184
+Stack trace:
+#0 /home/bov/public_html/vendor/yiisoft/yii2/console/Application.php(148): yii\console\Application->runAction('migrate-module', Array)
+#1 /home/bov/public_html/vendor/yiisoft/yii2/base/Application.php(392): yii\console\Application->handleRequest(Object(yii\console\Request))
+#2 /home/bov/public_html/yii(23): yii\base\Application->run()
+#3 {main}
+$_SERVER = [
+    'LS_COLORS' => 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;05;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=01;36:*.au=01;36:*.flac=01;36:*.m4a=01;36:*.mid=01;36:*.midi=01;36:*.mka=01;36:*.mp3=01;36:*.mpc=01;36:*.ogg=01;36:*.ra=01;36:*.wav=01;36:*.oga=01;36:*.opus=01;36:*.spx=01;36:*.xspf=01;36:',
+    'SSH_CONNECTION' => '179.6.27.223 47170 209.126.81.193 22',
+    'MODULES_RUN_QUARANTINE' => 'LD_LIBRARY_PATH LD_PRELOAD',
+    'LANG' => 'en_US.UTF-8',
+    'HISTCONTROL' => 'ignoredups',
+    'HISTTIMEFORMAT' => '%F %T ',
+    'HOSTNAME' => 'vmi547422.contaboserver.net',
+    'OLDPWD' => '/home/bov',
+    'S_COLORS' => 'auto',
+    'which_declare' => 'declare -f',
+    'XDG_SESSION_ID' => '16588',
+    'MODULES_CMD' => '/usr/share/Modules/libexec/modulecmd.tcl',
+    'USER' => 'bov',
+    'PWD' => '/home/bov/public_html',
+    'HOME' => '/home/bov',
+    'SSH_CLIENT' => '179.6.27.223 47170 22',
+    'LOADEDMODULES' => '',
+    'SSH_TTY' => '/dev/pts/1',
+    'MAIL' => '/var/spool/mail/bov',
+    'TERM' => 'xterm',
+    'SHELL' => '/bin/bash',
+    'SHLVL' => '1',
+    'MANPATH' => ':',
+    'MODULEPATH' => '/etc/scl/modulefiles:/usr/share/Modules/modulefiles:/etc/modulefiles:/usr/share/modulefiles',
+    'LOGNAME' => 'bov',
+    'DBUS_SESSION_BUS_ADDRESS' => 'unix:path=/run/user/1005/bus',
+    'XDG_RUNTIME_DIR' => '/run/user/1005',
+    'MODULEPATH_modshare' => '/usr/share/modulefiles:1:/usr/share/Modules/modulefiles:1:/etc/modulefiles:1',
+    'PATH' => '/home/bov/.local/bin:/home/bov/bin:/usr/local/cpanel/3rdparty/lib/path-bin:/usr/share/Modules/bin:/usr/local/cpanel/3rdparty/lib/path-bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/cpanel/composer/bin',
+    'MODULESHOME' => '/usr/share/Modules',
+    'HISTSIZE' => '1000',
+    'LESSOPEN' => '||/usr/bin/lesspipe.sh %s',
+    'BASH_FUNC_which%%' => '() {  ( alias;
+ eval ${which_declare} ) | /usr/bin/which --tty-only --read-alias --read-functions --show-tilde --show-dot "$@"
+}',
+    'BASH_FUNC_module%%' => '() {  _module_raw "$@" 2>&1
+}',
+    'BASH_FUNC__module_raw%%' => '() {  unset _mlshdbg;
+ if [ "${MODULES_SILENT_SHELL_DEBUG:-0}" = \'1\' ]; then
+ case "$-" in 
+ *v*x*)
+ set +vx;
+ _mlshdbg=\'vx\'
+ ;;
+ *v*)
+ set +v;
+ _mlshdbg=\'v\'
+ ;;
+ *x*)
+ set +x;
+ _mlshdbg=\'x\'
+ ;;
+ *)
+ _mlshdbg=\'\'
+ ;;
+ esac;
+ fi;
+ unset _mlre _mlIFS;
+ if [ -n "${IFS+x}" ]; then
+ _mlIFS=$IFS;
+ fi;
+ IFS=\' \';
+ for _mlv in ${MODULES_RUN_QUARANTINE:-};
+ do
+ if [ "${_mlv}" = "${_mlv##*[!A-Za-z0-9_]}" -a "${_mlv}" = "${_mlv#[0-9]}" ]; then
+ if [ -n "`eval \'echo ${\'$_mlv\'+x}\'`" ]; then
+ _mlre="${_mlre:-}${_mlv}_modquar=\'`eval \'echo ${\'$_mlv\'}\'`\' ";
+ fi;
+ _mlrv="MODULES_RUNENV_${_mlv}";
+ _mlre="${_mlre:-}${_mlv}=\'`eval \'echo ${\'$_mlrv\':-}\'`\' ";
+ fi;
+ done;
+ if [ -n "${_mlre:-}" ]; then
+ eval `eval ${_mlre} /usr/bin/tclsh /usr/share/Modules/libexec/modulecmd.tcl bash \'"$@"\'`;
+ else
+ eval `/usr/bin/tclsh /usr/share/Modules/libexec/modulecmd.tcl bash "$@"`;
+ fi;
+ _mlstatus=$?;
+ if [ -n "${_mlIFS+x}" ]; then
+ IFS=$_mlIFS;
+ else
+ unset IFS;
+ fi;
+ unset _mlre _mlv _mlrv _mlIFS;
+ if [ -n "${_mlshdbg:-}" ]; then
+ set -$_mlshdbg;
+ fi;
+ unset _mlshdbg;
+ return $_mlstatus
+}',
+    'BASH_FUNC_switchml%%' => '() {  typeset swfound=1;
+ if [ "${MODULES_USE_COMPAT_VERSION:-0}" = \'1\' ]; then
+ typeset swname=\'main\';
+ if [ -e /usr/share/Modules/libexec/modulecmd.tcl ]; then
+ typeset swfound=0;
+ unset MODULES_USE_COMPAT_VERSION;
+ fi;
+ else
+ typeset swname=\'compatibility\';
+ if [ -e /usr/share/Modules/libexec/modulecmd-compat ]; then
+ typeset swfound=0;
+ MODULES_USE_COMPAT_VERSION=1;
+ export MODULES_USE_COMPAT_VERSION;
+ fi;
+ fi;
+ if [ $swfound -eq 0 ]; then
+ echo "Switching to Modules $swname version";
+ source /usr/share/Modules/init/bash;
+ else
+ echo "Cannot switch to Modules $swname version, command not found";
+ return 1;
+ fi
+}',
+    'BASH_FUNC_scl%%' => '() {  if [ "$1" = "load" -o "$1" = "unload" ]; then
+ eval "module $@";
+ else
+ /usr/bin/scl "$@";
+ fi
+}',
+    'BASH_FUNC_ml%%' => '() {  module ml "$@"
+}',
+    '_' => '/usr/local/bin/php',
+    'PHP_SELF' => 'yii',
+    'SCRIPT_NAME' => 'yii',
+    'SCRIPT_FILENAME' => 'yii',
+    'PATH_TRANSLATED' => 'yii',
+    'DOCUMENT_ROOT' => '',
+    'REQUEST_TIME_FLOAT' => 1644771131.26782989501953125,
+    'REQUEST_TIME' => 1644771131,
+    'argv' => [
+        'yii',
+        'migrate-module',
+    ],
+    'argc' => 2,
+]
